### ISSUE TITLE
Implement the DBSCAN algorithm

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/clustering#3]
The DBSCAN algorithm should be implemented and able to take a list of potential core-micro-clusters as input. Coordinate this effort with the person implementing the core-micro-cluster class (see #2).

**Comment by OfficialHisha** [comment]
Done did it maybe?
See https://github.com/sea-shanty-2/clustering/commit/5d72121b49ce0672aad2c56067c066f61a46a2eb for reffewencei
